create table [dbo].[studentbaseball]
(
	[id] int identity(1,1) not null, 
    [studentid] int not null unique, 
    [statspictureid] int null, 
	[runningtime] decimal(18,2) null,
	[bats] varchar(1) null,
	[throws] varchar(1) null,
	[travelteam] varchar(100) null,
	[travelurl] varchar(255) null,
	[runningtimelocation] varchar(100) null,
	[runningtimelocationurl] varchar(255) null,
	[p] varchar(1) null,
	[c] varchar(1) null,
	[b1] varchar(1) null,
	[b2] varchar(1) null,
	[b3] varchar(1) null,
	[ss] varchar(1) null,
	[lf] varchar(1) null,
	[cf] varchar(1) null,
	[rf] varchar(1) null,
    [created] datetime not null default getdate(), 
    constraint [pk_studentbaseball_id] primary key clustered (id),
    constraint [fk_studentbaseball_student] foreign key (studentid) references [student](id), 
)
