create table [dbo].[studentbbhitting]
(
	[id] int identity(1,1) not null, 
    [studentid] int not null, 
    [category] varchar(100) not null default 'other games played', 
	[dateplayed]  date not null, 
	[teamplayed] varchar(255) not null,
	[plateappearances] int null default 0,
	[strikeouts] int null default 0,
	[walks] int null default 0,
	[hitbypitch] int null default 0,
	[sacflys] int null default 0,
	[sacbunts] int null default 0,
	[singles] int null default 0,
	[doubles] int null default 0,
	[triples] int null default 0,
	[homeruns] int null default 0,
	[runsbattediin] int null default 0,
	[runsscored] int null default 0,
	[stolenbases] int null default 0,
    [created] datetime not null default getdate(), 
    constraint [pk_studentbbhitting_id] primary key clustered (id),
    constraint [fk_studentbbhitting_student] foreign key (studentid) references [student](id), 
)
