CREATE TABLE [dbo].[student]
(
	[id] INT NOT NULL, 
    [firstName] VARCHAR(50) NULL, 
    [lastName] VARCHAR(50) NULL, 
    [primaryEmail] VARCHAR(100) NULL, 
    [highSchoolId] INT NULL, 
    [graduationYear] INT NULL, 
    [additionalInfo] VARCHAR(MAX) NULL, 
    [gpa] DECIMAL(18, 2) NULL, 
	[satTestDate] datetime null,
    [satScore] INT NULL, 
	[actTestDate] datetime null,
    [actScore] INT NULL, 
    [ncaaid] VARCHAR(50) NULL, 
    [phone] VARCHAR(10) NULL, 
    [streetAddress1] VARCHAR(255) NULL, 
    [streetAddress2] VARCHAR(255) NULL, 
    [city] VARCHAR(255) NULL, 
    [state] VARCHAR(2) NULL, 
    [zip] VARCHAR(10) NULL, 
    [displayAddrAndPhone] SMALLINT NULL, 
    [profilePictureId] INT NULL, 
	[height] varchar(10) NULL,
	[weight] varchar(10) NULL,
    [created] DATETIME NOT NULL default getdate(), 
	[collegemajor] varchar(100) null,
    CONSTRAINT [pk_student_id]  PRIMARY KEY CLUSTERED (id),
	CONSTRAINT [FK_student_userid] FOREIGN KEY (id) REFERENCES [users](id),
	CONSTRAINT [FK_student_highSchoolId] FOREIGN KEY (highSchoolId) REFERENCES [highSchool](id)
)
