create table [dbo].[users]
(
	[id] int identity(1,1) not null, 
    [profilename] varchar(50) not null, 
    [primaryemail] varchar(100) null, 
    [firstname] varchar(50) null, 
    [lastname] varchar(50) null, 
    [phone] varchar(10) null, 
    [streetaddress1] varchar(255) null, 
    [streetaddress2] varchar(255) null, 
    [city] varchar(255) null, 
    [state] varchar(2) null, 
    [zip] varchar(10) null, 
    [displayaddrandphone] smallint null, 
    [roleid] int not null, 
	[confirmationtoken] [nvarchar](128) null,
	[isconfirmed] [bit] null default ((0)),
	[lastpasswordfailuredate] [datetime] null,
	[passwordfailuressincelastsuccess] [int] not null default ((0)),
	[password] [nvarchar](128) not null,
	[passwordchangeddate] [datetime] null,
	[passwordsalt] [nvarchar](128) not null,
	[passwordverificationtoken] [nvarchar](128) null,
	[passwordverificationtokenexpirationdate] [datetime] null,
    [created] datetime not null default getdate(), 
    constraint [pk_users_id] primary key clustered (id),
    constraint [ck_profilename] unique (profilename),
    constraint [ck_primaryemail] unique (primaryemail),
    constraint [fk_users_userrole] foreign key (roleid) references [userroles](id), 
)
